import {ScrollView,StyleSheet,Text,View,Pressable} from "react-native";import{useLocalSearchParams,router}from"expo-router";import AppShell from"../../src/AppShell";import{theme}from"../../src/theme";
const DATA:any={
terms:{title:"Terms of Service",intro:"These Terms govern your use of AmoraLive and the services we provide.",sections:[["Use of AmoraLive","You must use AmoraLive lawfully, respectfully and in accordance with the Community Guidelines. You are responsible for activity on your account."],["Accounts & age","AmoraLive is an 18+ service. Keep your login details secure and provide accurate account information."],["Coins, gifts & memberships","Virtual coins, gifts and memberships are digital services. Purchases and subscription handling are subject to the applicable purchase terms and payment provider rules."],["Safety & moderation","We may restrict, suspend or remove accounts and content when necessary to protect users, enforce our rules or comply with law."],["Contact","For questions about these Terms, use the support/contact channels provided by AmoraLive."]]},
privacy:{title:"Privacy Policy",intro:"This page explains the categories of information AmoraLive uses to provide the service and protect the community.",sections:[["Identity & account","We may process account identifiers, authentication information, age-related information and profile information."],["Social activity","Interactions such as follows, likes, livestream participation, gifts and other platform activity may be processed to operate the service."],["Communications","Messages and related communication metadata are processed to provide messaging and protect users."],["Transactions","Purchase, subscription, virtual-coin and digital-gift information may be processed together with transaction status and identifiers."],["Security & rights","Technical and security information may be used for fraud prevention, account protection and service reliability. Applicable privacy rights and account-deletion options remain available."]]},
guidelines:{title:"Community Guidelines",intro:"AmoraLive is built for meaningful connections. Treat people with respect and help keep the platform safe.",sections:[["Respect","Harassment, bullying, stalking, intimidation and targeted abuse are not allowed."],["Safety","Threats, violence, exploitation, trafficking and dangerous criminal activity are prohibited."],["Adult & minors","Pornography, explicit sexual content and sexualization or exploitation of minors are prohibited. AmoraLive is 18+."],["Fraud & privacy","Scams, phishing, impersonation, doxxing, malicious disclosure of private information and account compromise are prohibited."],["Reporting","Use the reporting and blocking tools when you encounter harmful content or behavior. Moderation may remove content or restrict accounts."]]},
cookies:{title:"Cookies & Similar Technologies",intro:"AmoraLive uses necessary technologies to provide secure sessions and core functionality, with optional technologies handled according to applicable consent requirements.",sections:[["Strictly necessary","Authentication, session security, fraud prevention, load balancing and essential service functionality."],["Preferences","Language, interface and other choices may be remembered."],["Analytics","Where used, analytics can help improve performance, reliability and usability."],["Your choices","Where consent is required, optional technologies can be refused and preferences can be changed later."]]}
};
export default function Legal(){const{slug}=useLocalSearchParams<{slug:string}>();const d=DATA[String(slug)]||DATA.terms;return <AppShell><ScrollView style={s.p} contentContainerStyle={{paddingBottom:35}}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹</Text></Pressable><Text style={s.k}>AMORALIVE · LEGAL</Text><Text style={s.t}>{d.title}</Text><Text style={s.intro}>{d.intro}</Text>{d.sections.map((x:any[],i:number)=><View key={i} style={s.sec}><Text style={s.h}>{x[0]}</Text><Text style={s.body}>{x[1]}</Text></View>)}<Text style={s.footer}>Please use the current web policy as the authoritative full text if you need the complete legal document.</Text></ScrollView></AppShell>}
const s=StyleSheet.create({p:{flex:1,backgroundColor:theme.bg,padding:18},back:{color:"#fff",fontSize:40},k:{color:theme.pinkSoft,fontSize:8,fontWeight:"900",letterSpacing:2},t:{color:"#fff",fontSize:29,fontWeight:"900",marginTop:5},intro:{color:theme.muted,fontSize:10,lineHeight:16,marginTop:8},sec:{backgroundColor:theme.surface,borderRadius:17,padding:15,marginTop:9},h:{color:"#fff",fontSize:12,fontWeight:"900"},body:{color:"#d8d2e0",fontSize:9,lineHeight:15,marginTop:6},footer:{color:theme.dim,fontSize:8,lineHeight:13,marginTop:18}})
