export const LUXURY_GIFT_ART = {
  "Eternal Rose": "diamond-rose.svg",
  "Romantic Rose": "diamond-rose.svg",
  "Rose": "diamond-rose.svg",
  "Diamond Heart": "diamond-heart.svg",
  "Crystal Heart": "diamond-heart.svg",
  "Love Crown": "royal-crown.svg",
  "Diamond": "diamond-ring.svg",
  "Diamond Ring": "diamond-ring.svg",
  "Diamond Crown": "royal-crown.svg",
  "Gold Crown": "royal-crown.svg",
  "Crown": "royal-crown.svg",
  "Crown of Power": "royal-crown.svg",
  "Luxury Car": "luxury-car.svg",
  "Sports Car": "luxury-car.svg",
  "Private Jet": "private-jet.svg",
  "Gold Champagne": "champagne-royal.svg",
  "Champagne": "champagne-royal.svg",
  "Yacht": "royal-yacht.svg",
  "Golden Phoenix": "golden-phoenix.svg",
  "Phoenix": "golden-phoenix.svg",
  "Galaxy": "galaxy-heart.svg",
  "Universe": "galaxy-heart.svg",
  "Cosmic Heart": "galaxy-heart.svg",
  "Golden Palace": "diamond-palace.svg",
  "Palace": "diamond-palace.svg",
  "Amora Throne": "amora-throne.svg",
  "Royal Throne": "amora-throne.svg"
};
