const LUXURY_GIFT_ART = {
  "Eternal Rose": "eternal-rose.svg",
  "Crystal Heart": "crystal-heart.svg",
  "Kiss": "kiss.svg",
  "Love Letter": "love-letter.svg",
  "Diamond Heart": "diamond-heart.svg",
  "Forever Love": "forever-love.svg",
  "Romantic Rose": "romantic-rose.svg",
  "Cupid": "cupid.svg",
  "Love Crown": "love-crown.svg",
  "Eternal Love": "eternal-love.svg",
  "Diamond": "diamond.svg",
  "Diamond Crown": "diamond-crown.svg",
  "Gold Crown": "gold-crown.svg",
  "Luxury Car": "luxury-car.svg",
  "Private Jet": "private-jet.svg",
  "Gold Champagne": "gold-champagne.svg",
  "Diamond Ring": "diamond-ring.svg",
  "Treasure Chest": "treasure-chest.svg",
  "Golden Palace": "golden-palace.svg",
  "Royal Throne": "royal-throne.svg",
  "Galaxy": "galaxy.svg",
  "Moon": "moon.svg",
  "Planet": "planet.svg",
  "Cosmic Heart": "cosmic-heart.svg",
  "Supernova": "supernova.svg",
  "Black Hole": "black-hole.svg",
  "Cosmic Rose": "cosmic-rose.svg",
  "Star Portal": "star-portal.svg",
  "Universe": "universe.svg",
  "Infinity": "infinity.svg",
  "Lightning": "lightning.svg",
  "Fire": "fire.svg",
  "Thunder": "thunder.svg",
  "Phoenix": "phoenix.svg",
  "Dragon": "dragon.svg",
  "Energy Blast": "energy-blast.svg",
  "Golden Tiger": "golden-tiger.svg",
  "Warrior": "warrior.svg",
  "Crown of Power": "crown-of-power.svg",
  "Legendary Sword": "legendary-sword.svg",
  "Confetti": "confetti.svg",
  "Balloon": "balloon.svg",
  "Cupcake": "cupcake.svg",
  "Ice Cream": "ice-cream.svg",
  "Music": "music.svg",
  "Butterfly": "butterfly.svg",
  "Teddy Bear": "teddy-bear.svg",
  "Magic Box": "magic-box.svg",
  "Party Popper": "party-popper.svg",
  "Celebration": "celebration.svg"
};
module.exports = { LUXURY_GIFT_ART };
