import React, { useEffect, useState } from 'react';
import GiftIcon from './GiftIcon';
import { apiFetch } from '../lib/api';

export default function LuxuryGiftShelf({ limit = 100, title = 'Gift Collection' }) {
  const [items, setItems] = useState([]); const [loading, setLoading] = useState(true);
  useEffect(() => { let alive = true; apiFetch(`/gifts/history?direction=received&limit=${limit}`).then(async r => { if (!r.ok) throw new Error(); return r.json(); }).then(data => alive && setItems(Array.isArray(data) ? data : [])).catch(() => alive && setItems([])).finally(() => alive && setLoading(false)); return () => { alive = false; }; }, [limit]);
  const grouped = items.reduce((map, tx) => { const gift = tx.gift; if (!gift) return map; const key = gift.id; if (!map[key]) map[key] = { gift, quantity: 0 }; map[key].quantity += Number(tx.quantity || 1); return map; }, {});
  const collection = Object.values(grouped);
  return <section className="amora-gift-shelf-3d"><div className="amora-gift-shelf-head"><div><span className="amora-luxury-kicker">AMORA COLLECTION</span><h3>{title}</h3></div><div className="amora-gift-shelf-count">{collection.length}</div></div>
    {loading ? <div className="amora-gift-shelf-empty">Loading collection…</div> : collection.length === 0 ? <div className="amora-gift-shelf-empty">Gifts received from people you connect with will appear here.</div> : <div className="amora-gift-shelf-grid">{collection.map(({gift,quantity}) => <div key={gift.id} className="amora-gift-shelf-card"><div className="amora-gift-shelf-art"><GiftIcon name={gift.name} glyph={gift.glyph} rarity={gift.rarity} size={82} animated={gift.rarity === 'legendary' || gift.rarity === 'mythic'} /></div><div className="amora-gift-shelf-name">{gift.name}</div><div className="amora-gift-shelf-rarity">{gift.rarity || 'classic'}</div><div className="amora-gift-shelf-quantity">×{quantity}</div></div>)}</div>}
    <style jsx>{`.amora-gift-shelf-3d{background:linear-gradient(145deg,#171225,#211633 55%,#100b1c);border:1px solid rgba(255,255,255,.09);border-radius:26px;padding:20px;color:#fff;box-shadow:0 25px 80px rgba(0,0,0,.34),inset 0 1px rgba(255,255,255,.05)}.amora-gift-shelf-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:15px}.amora-gift-shelf-head h3{margin:5px 0 0;font-size:21px}.amora-gift-shelf-count{min-width:38px;height:38px;padding:0 10px;border-radius:13px;display:grid;place-items:center;color:#ffd86b;background:#ffd86b12;border:1px solid #ffd86b33;font-weight:900}.amora-gift-shelf-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(112px,1fr));gap:10px}.amora-gift-shelf-card{position:relative;text-align:center;padding:10px;border-radius:18px;border:1px solid rgba(255,255,255,.07);background:linear-gradient(180deg,#211a32,#181326);box-shadow:inset 0 1px rgba(255,255,255,.05);overflow:hidden}.amora-gift-shelf-art{height:84px;display:grid;place-items:center}.amora-gift-shelf-name{color:#fff;font-weight:800;font-size:11px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.amora-gift-shelf-rarity{margin-top:3px;color:#8f879e;font-size:8px;text-transform:uppercase;letter-spacing:1px}.amora-gift-shelf-quantity{display:inline-flex;margin-top:7px;padding:3px 8px;border-radius:999px;color:#ffd86b;background:#ffd86b12;border:1px solid #ffd86b22;font-size:10px;font-weight:900}.amora-gift-shelf-empty{padding:28px;color:#81788f;text-align:center;font-size:12px;line-height:1.5}`}</style>
  </section>;
}
