import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, ScrollView, StyleSheet, Text, View, Pressable } from "react-native";
import { router } from "expo-router";
import AppShell from "../src/AppShell";
import { theme } from "../src/theme";
import { api } from "../src/api/client";
import { useTranslation } from "../src/i18n";

export default function Levels(){const {t}=useTranslation();const perks=[["LV.1",t("levelsScreen.perk1Title"),t("levelsScreen.perk1Desc"),"🏅"],["LV.5",t("levelsScreen.perk2Title"),t("levelsScreen.perk2Desc"),"✨"],["LV.10",t("levelsScreen.perk3Title"),t("levelsScreen.perk3Desc"),"💬"],["LV.15",t("levelsScreen.perk4Title"),t("levelsScreen.perk4Desc"),"🎁"],["LV.20",t("levelsScreen.perk5Title"),t("levelsScreen.perk5Desc"),"💎"],["LV.25",t("levelsScreen.perk6Title"),t("levelsScreen.perk6Desc"),"🌟"],["LV.32",t("levelsScreen.perk7Title"),t("levelsScreen.perk7Desc"),"👑"],["LV.40",t("levelsScreen.perk8Title"),t("levelsScreen.perk8Desc"),"🌙"],["LV.50",t("levelsScreen.perk9Title"),t("levelsScreen.perk9Desc"),"👑"]];const [u,setU]=useState<any>(null),[loading,setLoading]=useState(true);const load=useCallback(async()=>{try{setU(await api.me());}finally{setLoading(false);}},[]);useEffect(()=>{load();},[load]);if(loading)return <AppShell><View style={s.center}><ActivityIndicator color={theme.pink}/></View></AppShell>;const level=Number(u?.level||0),xp=Number(u?.xp||0),progress=xp%100;return <AppShell><ScrollView style={s.page} contentContainerStyle={{paddingBottom:40}}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹</Text></Pressable><Text style={s.kicker}>{t("levelsScreen.kicker")}</Text><Text style={s.title}>{t("levelsScreen.title")}</Text><View style={s.hero}><Text style={s.level}>LV. {level}</Text><Text style={s.muted}>{xp.toLocaleString()} {t("levelsScreen.xpWord")}</Text><View style={s.track}><View style={[s.fill,{width:`${progress}%`}]}/></View><Text style={s.muted}>{100-progress} {t("levelsScreen.xpUntilNext")}</Text></View><Text style={s.section}>{t("levelsScreen.privileges")}</Text>{perks.map(([lv,title,desc,icon])=>{const n=Number(lv.replace("LV.",""));return <View key={lv} style={[s.card,n<=level&&s.unlocked]}><Text style={s.icon}>{icon}</Text><View style={{flex:1}}><Text style={s.lv}>{lv}</Text><Text style={s.name}>{title}</Text><Text style={s.muted}>{desc}</Text></View><Text style={n<=level?s.open:s.lock}>{n<=level?t("levelsScreen.unlocked"):t("levelsScreen.locked")}</Text></View>})}</ScrollView></AppShell>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:theme.bg,padding:18},back:{color:"#fff",fontSize:40},kicker:{color:theme.gold,fontSize:8,fontWeight:"900",letterSpacing:2.2},title:{color:"#fff",fontSize:29,fontWeight:"900",marginTop:5},hero:{backgroundColor:theme.surface,borderRadius:22,padding:20,marginTop:17,borderWidth:1,borderColor:"rgba(255,216,107,.18)"},level:{color:"#fff",fontSize:38,fontWeight:"900"},track:{height:7,backgroundColor:"#222",borderRadius:4,overflow:"hidden",marginTop:14},fill:{height:"100%",backgroundColor:theme.gold},section:{color:"#fff",fontSize:18,fontWeight:"900",marginTop:22,marginBottom:10},card:{flexDirection:"row",alignItems:"center",gap:10,backgroundColor:theme.surface,borderRadius:16,padding:13,marginBottom:8,borderWidth:1,borderColor:"rgba(255,255,255,.07)"},unlocked:{borderColor:"rgba(255,216,107,.2)"},icon:{fontSize:24},lv:{color:theme.gold,fontSize:8,fontWeight:"900"},name:{color:"#fff",fontSize:12,fontWeight:"900",marginTop:2},muted:{color:theme.muted,fontSize:9,lineHeight:15,marginTop:3},open:{color:theme.success,fontSize:8,fontWeight:"900"},lock:{color:theme.dim,fontSize:8,fontWeight:"900"},center:{flex:1,alignItems:"center",justifyContent:"center",backgroundColor:theme.bg}
});
