import { useCallback, useState } from "react";
import { router, useFocusEffect } from "expo-router";
import { View, Text, Pressable, StyleSheet, FlatList, ActivityIndicator, Image } from "react-native";
import { theme } from "../src/theme";
import AppShell from "../src/AppShell";
import { useTranslation } from "../src/i18n";

type LiveRoom = { id:string; title:string; category:string; viewer_count:number; thumbnail_url:string|null; host:{display_name:string;username:string;profile_photo:string|null} };

export default function Live() {
  const {t}=useTranslation();
  const [rooms,setRooms]=useState<LiveRoom[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  const load=useCallback(async()=>{ try { const { api }=await import("../src/api/client"); const data=await api.liveRooms(); setRooms(Array.isArray(data)?data:[]); setError(""); } catch(e:any){setError(e.message||t("liveScreen.errorLoad"));} finally{setLoading(false);} },[]);
  useFocusEffect(useCallback(()=>{load();},[load]));
  return <AppShell><View style={s.page}>
    <View style={s.header}><Pressable onPress={()=>router.back()} style={s.backBtn}><Text style={s.back}>‹</Text></Pressable><View><Text style={s.kicker}>{t("liveScreen.kicker")}</Text><Text style={s.title}>{t("liveScreen.title")}</Text></View><Pressable style={s.goLive} onPress={()=>router.push("/live/start")}><Text style={s.goLiveText}>{t("liveScreen.goLive")}</Text></Pressable></View>
    <View style={s.hero}><Text style={s.heroKicker}>{t("liveScreen.heroKicker")}</Text><Text style={s.heroTitle}>{t("liveScreen.heroTitle")}</Text><Text style={s.heroSub}>{t("liveScreen.heroSub")}</Text></View>
    {loading?<ActivityIndicator color={theme.pink} style={{marginTop:40}}/>:error?<Text style={s.muted}>{error}</Text>:rooms.length===0?<View style={s.empty}><Text style={s.emptyIcon}>✦</Text><Text style={s.emptyTitle}>{t("liveScreen.noOneLive")}</Text><Text style={s.muted}>{t("liveScreen.beFirst")}</Text></View>:<FlatList data={rooms} keyExtractor={item=>item.id} numColumns={2} columnWrapperStyle={s.columns} contentContainerStyle={s.list} showsVerticalScrollIndicator={false} renderItem={({item})=><Pressable style={s.card} onPress={()=>router.push(`/live/${item.id}`)}>
      <View style={s.thumb}>{item.thumbnail_url?<Image source={{uri:item.thumbnail_url}} style={s.thumbImg}/>:<View style={s.thumbFallback}><Text style={{fontSize:34}}>✦</Text></View>}<View style={s.liveBadge}><Text style={s.liveBadgeText}>LIVE</Text></View><View style={s.viewerBadge}><Text style={s.viewerText}>◉ {item.viewer_count}</Text></View></View>
      <View style={s.cardBody}><View style={s.hostRow}><View style={s.avatar}>{item.host?.profile_photo?<Image source={{uri:item.host.profile_photo}} style={s.avatarImg}/>:<Text style={s.avatarText}>{(item.host?.display_name||item.host?.username||"A")[0]}</Text>}</View><View style={{flex:1}}><Text style={s.host} numberOfLines={1}>{item.host?.display_name||item.host?.username}</Text><Text style={s.category}>#{item.category||t("liveScreen.generalFallback")}</Text></View></View><Text style={s.cardTitle} numberOfLines={2}>{item.title}</Text></View>
    </Pressable>}/>}
  </View></AppShell>;
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:theme.bg,padding:16},header:{flexDirection:"row",alignItems:"center",gap:10,paddingTop:8},backBtn:{width:38,height:38,borderRadius:13,backgroundColor:"rgba(255,255,255,.05)",alignItems:"center",justifyContent:"center",borderWidth:1,borderColor:"rgba(255,255,255,.08)"},back:{fontSize:31,color:"#fff",marginTop:-4},kicker:{color:theme.pinkSoft,fontSize:8,fontWeight:"900",letterSpacing:2},title:{fontSize:25,fontWeight:"900",color:"#fff"},goLive:{marginLeft:"auto",borderRadius:14,paddingHorizontal:12,paddingVertical:10,backgroundColor:theme.pink,shadowColor:theme.pink,shadowOpacity:.3,shadowRadius:14,shadowOffset:{width:0,height:6}},goLiveText:{color:"#fff",fontWeight:"900",fontSize:11},hero:{marginTop:16,padding:20,borderRadius:24,borderWidth:1,borderColor:"rgba(255,255,255,.09)",backgroundColor:theme.surface},heroKicker:{color:theme.gold,fontSize:8,fontWeight:"900",letterSpacing:2},heroTitle:{color:"#fff",fontSize:23,fontWeight:"900",marginTop:5},heroSub:{color:theme.muted,fontSize:11,lineHeight:17,marginTop:5},list:{paddingTop:16,paddingBottom:30},columns:{gap:10,marginBottom:10},card:{flex:1,borderRadius:20,overflow:"hidden",backgroundColor:theme.surface,borderWidth:1,borderColor:"rgba(255,255,255,.08)",shadowColor:"#000",shadowOpacity:.3,shadowRadius:18,shadowOffset:{width:0,height:8}},thumb:{aspectRatio:.78,backgroundColor:theme.surface2,position:"relative"},thumbImg:{width:"100%",height:"100%"},thumbFallback:{flex:1,alignItems:"center",justifyContent:"center",backgroundColor:theme.surface2},liveBadge:{position:"absolute",top:9,left:9,paddingHorizontal:8,paddingVertical:4,borderRadius:8,backgroundColor:theme.pink},liveBadgeText:{color:"#fff",fontSize:8,fontWeight:"900",letterSpacing:1},viewerBadge:{position:"absolute",right:8,top:8,paddingHorizontal:8,paddingVertical:4,borderRadius:10,backgroundColor:"rgba(5,3,12,.65)",borderWidth:1,borderColor:"rgba(255,255,255,.1)"},viewerText:{color:"#fff",fontSize:9,fontWeight:"800"},cardBody:{padding:10},hostRow:{flexDirection:"row",alignItems:"center",gap:7},avatar:{width:28,height:28,borderRadius:14,overflow:"hidden",backgroundColor:theme.purple,alignItems:"center",justifyContent:"center",borderWidth:1,borderColor:"rgba(255,255,255,.14)"},avatarImg:{width:"100%",height:"100%"},avatarText:{color:"#fff",fontWeight:"900"},host:{color:"#fff",fontWeight:"800",fontSize:10},category:{color:theme.dim,fontSize:8,marginTop:2},cardTitle:{color:"#fff",fontWeight:"900",fontSize:12,marginTop:9,lineHeight:16},muted:{color:theme.muted,textAlign:"center",marginTop:20,fontSize:12},empty:{flex:1,alignItems:"center",justifyContent:"center",paddingBottom:80},emptyIcon:{fontSize:55,color:theme.pink,textShadowColor:theme.pink,textShadowRadius:25},emptyTitle:{color:"#fff",fontSize:20,fontWeight:"900",marginTop:10}
});
