import {useEffect,useState} from "react";import{ActivityIndicator,Pressable,ScrollView,StyleSheet,Text,View}from"react-native";import{router}from"expo-router";import * as WebBrowser from "expo-web-browser";import AppShell from"../src/AppShell";import{theme}from"../src/theme";import{phase4Api}from"../src/phase4Api";import{api}from"../src/api/client";
// NOTE: unlike coins (app/wallet.tsx), there is currently no native-IAP
// verification endpoint for subscriptions on the backend — only Stripe
// checkout exists (/membership/checkout). That means this is Stripe-only
// for now. Apple requires auto-renewable subscriptions to go through
// StoreKit before an app can ship to the App Store — building that
// (server-to-server Apple/Google subscription receipt verification) is a
// separate backend task, not something this screen can work around.
export default function Membership(){const[plans,setPlans]=useState<any[]>([]),[current,setCurrent]=useState<any>(),[loading,setLoading]=useState(true),[error,setError]=useState(""),[busyId,setBusyId]=useState("");const load=async()=>{try{const[p,m]=await Promise.all([phase4Api.plans(),phase4Api.membership()]);setPlans(p?.plans||p||[]);setCurrent(m?.membership||m)}catch(e:any){setError(e.message||"Unable to load membership.")}finally{setLoading(false)}};useEffect(()=>{load()},[]);const subscribe=async(tier:string)=>{setBusyId(tier);setError("");try{const{checkoutUrl}=await api.membershipCheckout(tier);if(!checkoutUrl)throw new Error("Checkout is not available right now.");await WebBrowser.openBrowserAsync(checkoutUrl);await load()}catch(e:any){setError(e.message||"Unable to start membership.")}finally{setBusyId("")}};return <AppShell><ScrollView style={s.page}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹</Text></Pressable><Text style={s.kicker}>AMORA PRIVILEGE</Text><Text style={s.title}>VIP Membership</Text><Text style={s.sub}>A more beautiful way to enjoy AmoraLive.</Text>{loading?<ActivityIndicator color={theme.pink}/>:error?<Text style={s.error}>{error}</Text>:<><View style={s.current}><Text style={s.label}>YOUR MEMBERSHIP</Text><Text style={s.vip}>{current?.name||current?.plan?.name||"Free"}</Text></View>{plans.map((p,i)=><View style={s.card} key={p.id||p.tier||i}><Text style={s.plan}>{p.name||p.title||p.label||"VIP"}</Text><Text style={s.price}>{p.price_display||p.price||"Premium"}</Text>{(p.benefits||p.perks||["VIP badge & profile frame","Exclusive gifts","VIP rooms","Monthly perks"]).slice(0,5).map((x:any,j:number)=><Text style={s.perk} key={j}>✓ {typeof x==="string"?x:x.name}</Text>)}<Pressable style={s.button} disabled={busyId===String(p.tier||p.id)} onPress={()=>subscribe(String(p.tier||p.id))}><Text style={s.bt}>{busyId===String(p.tier||p.id)?"…":"Choose VIP"}</Text></Pressable></View>)}</>}</ScrollView></AppShell>}const s=StyleSheet.create({page:{flex:1,backgroundColor:theme.bg,padding:18},back:{color:"#fff",fontSize:40},kicker:{color:theme.gold,fontSize:8,fontWeight:"900",letterSpacing:2},title:{color:"#fff",fontSize:30,fontWeight:"900"},sub:{color:theme.muted,fontSize:10,marginBottom:15},current:{backgroundColor:"#171321",borderRadius:20,padding:18,borderWidth:1,borderColor:"#6f4f8c",marginBottom:12},label:{color:theme.dim,fontSize:7,fontWeight:"900"},vip:{color:theme.gold,fontSize:23,fontWeight:"900",marginTop:6},card:{backgroundColor:theme.surface,borderRadius:20,padding:17,marginBottom:10},plan:{color:"#fff",fontSize:17,fontWeight:"900"},price:{color:theme.pinkSoft,fontSize:10,marginBottom:10},perk:{color:"#ddd7e8",fontSize:9,marginVertical:3},button:{marginTop:12,backgroundColor:theme.pink,borderRadius:13,paddingVertical:13,alignItems:"center"},bt:{color:"#fff",fontWeight:"900",fontSize:10},error:{color:"#ff8bad",textAlign:"center",marginTop:20}});
