import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import AppShell from "../src/AppShell";
import { api } from "../src/phase2Api";

export default function Membership(){
 const [current,setCurrent]=useState<any>(null),[plans,setPlans]=useState<any[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[error,setError]=useState("");
 const load=useCallback(async()=>{try{const [m,p]=await Promise.all([api.membership(),api.membershipPlans()]);setCurrent(m);setPlans(p||[]);}catch(e:any){setError(e.message||"Unable to load membership.");}finally{setLoading(false);}},[]);
 useEffect(()=>{load();},[load]);
 const choose=async(tier:string)=>{setBusy(tier);try{const r=await api.membershipCheckout(tier);if(r?.checkoutUrl)router.push({pathname:"/checkout",params:{url:r.checkoutUrl}});else await load();}catch(e:any){setError(e.message||"Unable to start membership checkout.");}finally{setBusy("");}};
 const cancel=()=>Alert.alert("Cancel membership?","Your current benefits will remain according to the membership policy.",[{text:"Keep",style:"cancel"},{text:"Cancel membership",style:"destructive",onPress:async()=>{try{await api.membershipCancel();await load();}catch(e:any){setError(e.message||"Unable to cancel membership.");}}}]);
 if(loading)return <AppShell><View style={s.center}><ActivityIndicator color={theme.gold}/></View></AppShell>;
 return <AppShell><ScrollView style={s.page} contentContainerStyle={{paddingBottom:40}}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹</Text></Pressable><Text style={s.kicker}>AMORA PRIVATE CLUB</Text><Text style={s.title}>Membership</Text><Text style={s.subtitle}>More visibility. More expression. More luxury.</Text>{current?.tier&&<View style={s.current}><Text style={s.currentLabel}>CURRENT MEMBERSHIP</Text><Text style={s.currentTier}>{String(current.tier).toUpperCase()}</Text><Text style={s.muted}>{current.expires_at?`Renews / expires ${new Date(current.expires_at).toLocaleDateString()}`:"Active"}</Text><Pressable onPress={cancel}><Text style={s.cancel}>Cancel membership</Text></Pressable></View>}{!!error&&<Text style={s.error}>{error}</Text>}{plans.map(p=><View key={p.tier} style={[s.card,p.tier===current?.tier&&s.selected]}><Text style={s.badge}>{String(p.tier||"VIP").toUpperCase()}</Text><Text style={s.plan}>{p.name||p.tier}</Text><Text style={s.price}>{p.currency||"USD"} {p.price}{p.interval?` / ${p.interval}`:""}</Text><Text style={s.description}>{p.description||"Premium Amora benefits."}</Text>{Array.isArray(p.benefits)&&p.benefits.map((b:string,i:number)=><Text key={i} style={s.benefit}>✓ {b}</Text>)}{p.tier!==current?.tier&&<Pressable disabled={busy===p.tier} onPress={()=>choose(p.tier)} style={s.join}><Text style={s.joinText}>{busy===p.tier?"Loading…":"Choose plan"}</Text></Pressable>}</View>)}</ScrollView></AppShell>;
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:theme.bg,padding:18},back:{color:"#fff",fontSize:40},kicker:{color:theme.gold,fontSize:8,fontWeight:"900",letterSpacing:2.2},title:{color:"#fff",fontSize:30,fontWeight:"900",marginTop:5},subtitle:{color:theme.muted,fontSize:10,marginTop:4},current:{backgroundColor:"#241d12",borderRadius:20,padding:17,marginTop:17,borderWidth:1,borderColor:"rgba(255,216,107,.3)"},currentLabel:{color:theme.gold,fontSize:8,fontWeight:"900",letterSpacing:1},currentTier:{color:"#fff",fontSize:23,fontWeight:"900",marginTop:5},muted:{color:theme.muted,fontSize:9,marginTop:4},cancel:{color:"#ff8080",fontSize:9,fontWeight:"800",marginTop:12},error:{color:"#ff8bad",textAlign:"center",marginTop:10},card:{backgroundColor:theme.surface,borderRadius:21,padding:18,marginTop:12,borderWidth:1,borderColor:"rgba(255,255,255,.07)"},selected:{borderColor:"rgba(255,216,107,.35)"},badge:{color:theme.gold,fontSize:8,fontWeight:"900",letterSpacing:1},plan:{color:"#fff",fontSize:20,fontWeight:"900",marginTop:5},price:{color:theme.gold,fontSize:14,fontWeight:"900",marginTop:4},description:{color:theme.muted,fontSize:10,lineHeight:16,marginTop:8},benefit:{color:"#eee",fontSize:10,marginTop:7},join:{marginTop:14,backgroundColor:theme.gold,borderRadius:11,paddingVertical:12,alignItems:"center"},joinText:{color:"#17110a",fontWeight:"900",fontSize:10},center:{flex:1,alignItems:"center",justifyContent:"center",backgroundColor:theme.bg}
});
