import { useCallback, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router, useFocusEffect } from "expo-router";
import { api } from "../src/api/client";
import AppShell from "../src/AppShell";
import { theme } from "../src/theme";

export default function Outfits() {
  const [items,setItems]=useState<any[]>([]),[owned,setOwned]=useState<any[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[error,setError]=useState("");
  const load=useCallback(async()=>{try{const [a,b]=await Promise.all([api.storeCatalog(),api.storeMy()]);setItems(a||[]);setOwned(b||[]);setError("");}catch(e:any){setError(e.message||"Unable to load your collection.");}finally{setLoading(false);}},[]);
  useFocusEffect(useCallback(()=>{load();},[load]));
  const ownedMap=new Map(owned.map(x=>[x.cosmetic_id,x]));
  const toggle=async(id:string)=>{const o=ownedMap.get(id);if(!o)return;setBusy(id);try{if(o.is_equipped)await api.unequipCosmetic(id);else await api.equipCosmetic(id);await load();}catch(e:any){setError(e.message||"Unable to update your look.");}finally{setBusy("");}};
  if(loading)return <AppShell><View style={s.center}><ActivityIndicator color={theme.pink}/></View></AppShell>;
  return <AppShell><ScrollView style={s.page} contentContainerStyle={{paddingBottom:30}}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹</Text></Pressable><Text style={s.kicker}>AMORA COLLECTION</Text><Text style={s.title}>Dress your aura.</Text><Text style={s.muted}>Frames, effects, badges and profile styles that make your Amora identity yours.</Text>{!!error&&<Text style={s.error}>{error}</Text>}<View style={s.grid}>{items.map((item:any)=><View key={item.id} style={s.card}><View style={s.art}><Text style={s.artText}>{item.type==="frame"?"◉":item.type==="badge"?"✦":"◇"}</Text></View><Text style={s.name} numberOfLines={1}>{item.name}</Text><Text style={s.meta}>{item.type} · {item.price_coins} coins</Text>{ownedMap.has(item.id)?<Pressable style={[s.button,ownedMap.get(item.id)?.is_equipped&&s.active]} onPress={()=>toggle(item.id)} disabled={busy===item.id}><Text style={s.buttonText}>{busy===item.id?"…":ownedMap.get(item.id)?.is_equipped?"Equipped":"Equip"}</Text></Pressable>:<Text style={s.ownedHint}>Not owned</Text>}</View>)}</View></ScrollView></AppShell>;
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:theme.bg,padding:18},back:{color:"#fff",fontSize:40},kicker:{color:theme.pinkSoft,fontSize:8,fontWeight:"900",letterSpacing:2.3},title:{color:"#fff",fontSize:29,fontWeight:"900",marginTop:5},muted:{color:theme.muted,fontSize:11,lineHeight:17,marginTop:4},error:{color:"#ff8bad",fontSize:10,textAlign:"center",marginTop:10},grid:{flexDirection:"row",flexWrap:"wrap",gap:10,marginTop:18},card:{width:"48%",minHeight:180,padding:12,borderRadius:20,backgroundColor:theme.surface,borderWidth:1,borderColor:"rgba(255,255,255,.08)"},art:{height:90,borderRadius:17,backgroundColor:"rgba(255,79,163,.06)",borderWidth:1,borderColor:"rgba(255,79,163,.13)",alignItems:"center",justifyContent:"center"},artText:{fontSize:42,color:theme.pink},name:{color:"#fff",fontSize:11,fontWeight:"900",marginTop:10},meta:{color:theme.dim,fontSize:8,marginTop:3},button:{marginTop:10,borderRadius:10,paddingVertical:9,backgroundColor:theme.pink,alignItems:"center"},active:{backgroundColor:theme.purple},buttonText:{color:"#fff",fontWeight:"900",fontSize:9},ownedHint:{color:theme.dim,fontSize:8,marginTop:12},center:{flex:1,alignItems:"center",justifyContent:"center",backgroundColor:theme.bg}});
