import { useCallback, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router, useFocusEffect } from "expo-router";
import { api } from "../src/api/client";
import AppShell from "../src/AppShell";
import { theme } from "../src/theme";

export default function Rewards() {
  const [status,setStatus]=useState<any>(null),[history,setHistory]=useState<any[]>([]),[loading,setLoading]=useState(true),[claiming,setClaiming]=useState(false),[error,setError]=useState("");
  const load=useCallback(async()=>{try{const [a,b]=await Promise.all([api.dailyRewardStatus(),api.dailyRewardHistory()]);setStatus(a);setHistory(b||[]);setError("");}catch(e:any){setError(e.message||"Unable to load rewards.");}finally{setLoading(false);}},[]);
  useFocusEffect(useCallback(()=>{load();},[load]));
  const claim=async()=>{if(!status?.canClaimToday||claiming)return;setClaiming(true);try{await api.claimDailyReward();await load();}catch(e:any){setError(e.message||"Unable to claim reward.");}finally{setClaiming(false);}};
  if(loading)return <AppShell><View style={s.center}><ActivityIndicator color={theme.pink}/></View></AppShell>;
  return <AppShell><ScrollView style={s.page} contentContainerStyle={{paddingBottom:30}}>
    <Pressable onPress={()=>router.back()}><Text style={s.back}>‹</Text></Pressable><Text style={s.kicker}>AMORA REWARDS</Text><Text style={s.title}>Come back. Get rewarded.</Text>
    <View style={s.hero}><Text style={s.heroKicker}>CURRENT STREAK</Text><Text style={s.streak}>{status?.currentStreak||0} days</Text><Text style={s.muted}>Best streak: {status?.bestStreak||0} days</Text><Pressable style={[s.button,!status?.canClaimToday&&s.disabled]} disabled={!status?.canClaimToday||claiming} onPress={claim}><Text style={s.buttonText}>{claiming?"Claiming…":status?.canClaimToday?`Claim +${Number(status?.nextReward?.coins||0).toLocaleString()} coins`:"Claimed today"}</Text></Pressable></View>
    {!!error&&<Text style={s.error}>{error}</Text>}<Text style={s.section}>7-day cycle</Text><View style={s.days}>{(status?.calendar||[]).map((d:any)=><View key={d.day} style={[s.day,d.day===status?.nextReward?.dayInCycle&&s.dayActive]}><Text style={s.dayNum}>DAY {d.day}</Text><Text style={s.dayCoins}>{d.coins}</Text><Text style={s.dayLabel}>coins</Text></View>)}</View>
    <Text style={s.section}>Recent claims</Text>{history.length===0?<Text style={s.muted}>No claims yet.</Text>:history.map((h:any)=><View key={h.id} style={s.history}><Text style={s.historyDay}>Day {h.day_number}</Text><Text style={s.historyDate}>{new Date(h.claimed_at).toLocaleDateString()}</Text><Text style={s.historyCoins}>+{h.coins_awarded}</Text></View>)}
  </ScrollView></AppShell>;
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:theme.bg,padding:18},back:{color:"#fff",fontSize:40},kicker:{color:theme.gold,fontSize:8,fontWeight:"900",letterSpacing:2.3},title:{color:"#fff",fontSize:29,fontWeight:"900",marginTop:5},hero:{marginTop:18,padding:22,borderRadius:25,backgroundColor:theme.surface,borderWidth:1,borderColor:"rgba(255,216,107,.2)"},heroKicker:{color:theme.gold,fontSize:8,fontWeight:"900",letterSpacing:2},streak:{color:"#fff",fontSize:38,fontWeight:"900",marginTop:5},muted:{color:theme.muted,fontSize:11,lineHeight:17,marginTop:4},button:{marginTop:17,backgroundColor:theme.pink,borderRadius:14,paddingVertical:13,alignItems:"center"},disabled:{opacity:.45},buttonText:{color:"#fff",fontWeight:"900",fontSize:11},error:{color:"#ff8bad",textAlign:"center",fontSize:10,marginTop:10},section:{color:"#fff",fontSize:18,fontWeight:"900",marginTop:22,marginBottom:10},days:{flexDirection:"row",flexWrap:"wrap",gap:8},day:{width:"31%",minHeight:80,padding:10,borderRadius:15,backgroundColor:theme.surface,borderWidth:1,borderColor:"rgba(255,255,255,.07)"},dayActive:{borderColor:theme.pink,backgroundColor:"rgba(255,79,163,.08)"},dayNum:{color:theme.dim,fontSize:7,fontWeight:"900",letterSpacing:1},dayCoins:{color:theme.gold,fontSize:17,fontWeight:"900",marginTop:7},dayLabel:{color:theme.dim,fontSize:7},history:{flexDirection:"row",alignItems:"center",backgroundColor:theme.surface,borderRadius:14,padding:13,marginBottom:7},historyDay:{color:"#fff",fontWeight:"800",flex:1},historyDate:{color:theme.dim,fontSize:9},historyCoins:{color:theme.success,fontWeight:"900",marginLeft:10},center:{flex:1,alignItems:"center",justifyContent:"center",backgroundColor:theme.bg}});
