import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import AppShell from "../src/AppShell";
import { theme } from "../src/theme";
import { phase1Request } from "../src/phase1Api";
import { useTranslation } from "../src/i18n";

export default function Safety(){
 const {t}=useTranslation();
 const tabLabels:Record<string,string>={security:t("safetyScreen.tabSecurity"),sessions:t("safetyScreen.tabSessions"),blocked:t("safetyScreen.tabBlocked"),muted:t("safetyScreen.tabMuted"),reports:t("safetyScreen.tabReports")};
 const [tab,setTab]=useState("security"),[security,setSecurity]=useState<any>(null),[sessions,setSessions]=useState<any[]>([]),[blocked,setBlocked]=useState<any[]>([]),[muted,setMuted]=useState<any[]>([]),[reports,setReports]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);try{const [sec,ss,b,m,r]=await Promise.all([phase1Request("/safety/security/overview"),phase1Request("/safety/sessions"),phase1Request("/users/me/blocks"),phase1Request("/safety/muted"),phase1Request("/safety/my-reports")]);setSecurity(sec);setSessions(ss||[]);setBlocked(b?.blocks||b||[]);setMuted(m||[]);setReports(r||[]);}catch(e:any){setError(e.message||t("safetyScreen.errorLoad"));}finally{setLoading(false);}},[]);
 useEffect(()=>{load();},[load]);
 const revoke=async(id:string)=>{try{await phase1Request(`/safety/sessions/${id}`,{method:"DELETE"});setSessions(x=>x.filter(s=>s.id!==id));}catch{}};
 const revokeOthers=async()=>{try{await phase1Request("/safety/sessions/revoke-others",{method:"POST"});await load();}catch{}};
 const unblock=async(id:string)=>{try{await phase1Request("/users/me/unblock",{method:"POST",body:JSON.stringify({userId:id})});setBlocked(x=>x.filter(u=>u.id!==id));}catch{}};
 const unmute=async(id:string)=>{try{await phase1Request("/safety/unmute",{method:"POST",body:JSON.stringify({userId:id})});setMuted(x=>x.filter(u=>u.id!==id));}catch{}};
 if(loading)return <AppShell><View style={s.center}><ActivityIndicator color={theme.pink}/></View></AppShell>;
 return <AppShell><ScrollView style={s.page} contentContainerStyle={{paddingBottom:40}}>
  <Text style={s.kicker}>{t("safetyScreen.kicker")}</Text><Text style={s.title}>{t("safetyScreen.title")}</Text>{!!error&&<Text style={s.error}>{error}</Text>}
  {security&&<View style={s.hero}><View style={s.score}><Text style={s.scoreNum}>{security.score ?? "—"}</Text><Text style={s.out}>/100</Text></View><View style={{flex:1}}><Text style={s.heroTitle}>{security.score>=90?t("safetyScreen.excellentProtection"):security.score>=75?t("safetyScreen.strongProtection"):t("safetyScreen.protectionNeedsAttention")}</Text><Text style={s.muted}>{security.recommendations?.[0]||t("safetyScreen.reviewSecurityDefault")}</Text></View></View>}
  <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.tabs}>{["security","sessions","blocked","muted","reports"].map(tabKey=><Pressable key={tabKey} onPress={()=>setTab(tabKey)} style={[s.tab,tab===tabKey&&s.active]}><Text style={s.tabText}>{tabLabels[tabKey]}</Text></Pressable>)}</ScrollView>
  {tab==="security"&&<View style={s.card}><Text style={s.section}>{t("safetyScreen.securityOverview")}</Text><Text style={s.muted}>{t("safetyScreen.emailVerifiedLabel")} {security?.emailVerified?t("safetyScreen.yes"):t("safetyScreen.review")}</Text><Text style={s.muted}>{t("safetyScreen.activeSessionsLabel")} {security?.activeSessions??sessions.length}</Text><Text style={s.muted}>{t("safetyScreen.privacyConfiguredLabel")} {security?.privacyConfigured?t("safetyScreen.yes"):t("safetyScreen.review")}</Text></View>}
  {tab==="sessions"&&<View>{sessions.length>1&&<Pressable style={s.revokeAll} onPress={()=>Alert.alert(t("safetyScreen.logOutOtherDevicesTitle"),t("safetyScreen.staySignedInHere"),[{text:t("common.cancel")},{text:t("common.continue"),onPress:revokeOthers}])}><Text style={s.danger}>{t("safetyScreen.logOutAllOtherDevices")}</Text></Pressable>}{sessions.map(x=><View key={x.id} style={s.row}><View style={{flex:1}}><Text style={s.rowTitle}>{x.device_info||t("safetyScreen.unknownDevice")}</Text><Text style={s.muted}>{x.ip_address||t("safetyScreen.unknownLocation")}</Text></View><Pressable onPress={()=>revoke(x.id)}><Text style={s.action}>{t("safetyScreen.revoke")}</Text></Pressable></View>)}</View>}
  {tab==="blocked"&&<List items={blocked} empty={t("safetyScreen.noBlockedUsers")} action={t("safetyScreen.unblock")} onAction={unblock}/>}
  {tab==="muted"&&<List items={muted} empty={t("safetyScreen.noMutedUsers")} action={t("safetyScreen.unmute")} onAction={unmute}/>}
  {tab==="reports"&&<View>{reports.length?reports.map(r=><View key={r.id} style={s.row}><View style={{flex:1}}><Text style={s.rowTitle}>{r.target_type} · {String(r.category||"").replace(/_/g," ")}</Text><Text style={s.muted}>{r.status}</Text></View></View>):<Text style={s.empty}>{t("safetyScreen.noReportsSubmitted")}</Text>}</View>}
 </ScrollView></AppShell>;
}
function List({items,empty,action,onAction}:{items:any[],empty:string,action:string,onAction:(id:string)=>void}){const {t}=useTranslation();return <View>{items.length?items.map(x=><View key={x.id} style={s.row}><Text style={s.rowTitle}>{x.display_name||x.username||t("safetyScreen.userFallback")}</Text><Pressable onPress={()=>onAction(x.id)}><Text style={s.action}>{action}</Text></Pressable></View>):<Text style={s.empty}>{empty}</Text>}</View>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:theme.bg,padding:18},kicker:{color:theme.gold,fontSize:8,fontWeight:"900",letterSpacing:2.2},title:{color:"#fff",fontSize:30,fontWeight:"900",marginTop:5},error:{color:"#ff8bad",textAlign:"center",marginVertical:10},hero:{marginTop:16,padding:17,borderRadius:22,backgroundColor:theme.surface,borderWidth:1,borderColor:"rgba(255,216,107,.18)",flexDirection:"row",gap:14,alignItems:"center"},score:{width:72,height:72,borderRadius:36,borderWidth:2,borderColor:theme.gold,alignItems:"center",justifyContent:"center"},scoreNum:{color:"#fff",fontSize:24,fontWeight:"900"},out:{color:theme.dim,fontSize:8},heroTitle:{color:"#fff",fontSize:15,fontWeight:"900"},muted:{color:theme.muted,fontSize:10,lineHeight:16,marginTop:4},tabs:{gap:7,paddingVertical:14},tab:{paddingVertical:8,paddingHorizontal:12,borderRadius:16,borderWidth:1,borderColor:"rgba(255,255,255,.08)"},active:{backgroundColor:theme.pink,borderColor:theme.pink},tabText:{color:"#fff",fontSize:9,fontWeight:"900"},card:{backgroundColor:theme.surface,borderRadius:18,padding:16,borderWidth:1,borderColor:"rgba(255,255,255,.07)"},section:{color:"#fff",fontSize:16,fontWeight:"900"},row:{flexDirection:"row",alignItems:"center",padding:14,backgroundColor:theme.surface,borderRadius:14,marginBottom:7},rowTitle:{color:"#fff",fontSize:11,fontWeight:"800",flex:1},action:{color:theme.pink,fontSize:10,fontWeight:"900"},revokeAll:{padding:13,borderRadius:12,backgroundColor:"rgba(255,80,80,.1)",marginBottom:10,alignItems:"center"},danger:{color:"#ff8080",fontWeight:"900"},empty:{color:theme.muted,textAlign:"center",paddingVertical:35},center:{flex:1,alignItems:"center",justifyContent:"center",backgroundColor:theme.bg}
});
