import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Image, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import AppShell from "../src/AppShell";
import { theme } from "../src/theme";
import { api } from "../src/api/client";

export default function Store(){const [items,setItems]=useState<any[]>([]),[owned,setOwned]=useState<any[]>([]),[balance,setBalance]=useState(0),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[error,setError]=useState("");
 const load=useCallback(async()=>{try{const [a,b,w]=await Promise.all([api.storeCatalog(),api.storeMy(),api.wallet()]);setItems(a||[]);setOwned(b||[]);setBalance(w.balance||0);}catch(e:any){setError(e.message||"Unable to load the store.");}finally{setLoading(false);}},[]);useEffect(()=>{load();},[load]);const ownedIds=new Set(owned.map(x=>x.cosmetic_id));
 const buy=async(id:string)=>{setBusy(id);try{await api.storePurchase(id);await load();}catch(e:any){setError(e.message||"Purchase failed.");}finally{setBusy("");}};
 const equip=async(id:string,is:boolean)=>{setBusy(id);try{if(is)await api.unequipCosmetic(id);else await api.equipCosmetic(id);await load();}catch(e:any){setError(e.message||"Unable to update item.");}finally{setBusy("");}};
 if(loading)return <AppShell><View style={s.center}><ActivityIndicator color={theme.pink}/></View></AppShell>;
 return <AppShell><ScrollView style={s.page} contentContainerStyle={{paddingBottom:40}}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹</Text></Pressable><View style={s.head}><View><Text style={s.kicker}>AMORA LUXURY VAULT</Text><Text style={s.title}>Boutique</Text></View><Text style={s.balance}>🪙 {balance}</Text></View>{!!error&&<Text style={s.error}>{error}</Text>}<View style={s.grid}>{items.map(i=>{const o=owned.find(x=>x.cosmetic_id===i.id);return <View key={i.id} style={s.card}><View style={s.art}>{i.image_url?<Image source={{uri:i.image_url}} style={s.image}/>:<Text style={{fontSize:38}}>✨</Text>}</View><Text style={s.name}>{i.name}</Text><Text style={s.meta}>{i.duration_days?`${i.duration_days} days`:"Permanent"} · 🪙 {i.price_coins}</Text>{o?<Pressable disabled={busy===i.id} onPress={()=>equip(i.id,!!o.is_equipped)} style={[s.button,o.is_equipped&&s.active]}><Text style={s.btn}>{busy===i.id?"…":o.is_equipped?"Equipped ✓":"Equip"}</Text></Pressable>:<Pressable disabled={busy===i.id||balance<i.price_coins} onPress={()=>buy(i.id)} style={[s.button,balance<i.price_coins&&s.disabled]}><Text style={s.btn}>{busy===i.id?"Buying…":balance<i.price_coins?"Not enough coins":"Buy"}</Text></Pressable>}</View>})}</View></ScrollView></AppShell>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:theme.bg,padding:18},back:{color:"#fff",fontSize:40},head:{flexDirection:"row",alignItems:"center",justifyContent:"space-between"},kicker:{color:theme.gold,fontSize:8,fontWeight:"900",letterSpacing:2},title:{color:"#fff",fontSize:29,fontWeight:"900"},balance:{color:theme.gold,fontWeight:"900"},error:{color:"#ff8bad",textAlign:"center",marginVertical:10},grid:{flexDirection:"row",flexWrap:"wrap",gap:10,marginTop:16},card:{width:"48%",backgroundColor:theme.surface,borderRadius:18,padding:12,borderWidth:1,borderColor:"rgba(255,255,255,.08)"},art:{height:130,borderRadius:14,backgroundColor:"#171325",alignItems:"center",justifyContent:"center",overflow:"hidden"},image:{width:"100%",height:"100%"},name:{color:"#fff",fontWeight:"900",fontSize:11,marginTop:9},meta:{color:theme.dim,fontSize:8,marginTop:3},button:{marginTop:9,backgroundColor:theme.pink,borderRadius:9,paddingVertical:8,alignItems:"center"},active:{backgroundColor:theme.purple},disabled:{opacity:.35},btn:{color:"#fff",fontWeight:"900",fontSize:9},center:{flex:1,alignItems:"center",justifyContent:"center",backgroundColor:theme.bg}
});
