import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import AppShell from "../src/AppShell";
import { theme } from "../src/theme";
import { phase1Request } from "../src/phase1Api";

export default function Studio(){const [o,setO]=useState<any>(null),[a,setA]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=useCallback(async()=>{try{const [ov,an]=await Promise.all([phase1Request("/creator-studio/overview"),phase1Request("/creator-studio/analytics?days=30")]);setO(ov);setA(an||[]);}catch(e:any){setError(e.message||"Unable to load Creator Studio.");}finally{setLoading(false);}},[]);
 useEffect(()=>{load();},[load]);if(loading)return <AppShell><View style={s.center}><ActivityIndicator color={theme.pink}/></View></AppShell>;
 const stats=[["Followers",o?.totalFollowers??0],["New this week",`+${o?.newFollowersThisWeek??0}`],["Streams",o?.totalStreams??0],["Live time",`${o?.totalLiveMinutes??0}m`],["Peak viewers",o?.peakViewers??0],["Gifts received",o?.totalGiftsReceived??0],["Earnings",`🪙 ${o?.totalEarnings??0}`],["Level",o?.level??0]];
 return <AppShell><ScrollView style={s.page} contentContainerStyle={{paddingBottom:40}}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹</Text></Pressable><Text style={s.kicker}>AMORA CREATOR</Text><Text style={s.title}>Creator Studio</Text>{!!error&&<Text style={s.error}>{error}</Text>}<View style={s.grid}>{stats.map(x=><View key={x[0]} style={s.stat}><Text style={s.value}>{x[1]}</Text><Text style={s.label}>{x[0]}</Text></View>)}</View><Text style={s.section}>Quick tools</Text><View style={s.tools}><Pressable style={s.tool} onPress={()=>router.push("/live/start")}><Text style={s.toolText}>🔴 Go Live</Text></Pressable><Pressable style={s.tool} onPress={()=>router.push("/missions")}><Text style={s.toolText}>🎯 Missions</Text></Pressable><Pressable style={s.tool} onPress={()=>router.push("/wallet")}><Text style={s.toolText}>🎁 Wallet</Text></Pressable></View><Text style={s.section}>Last 30 days</Text>{a.slice(-10).reverse().map((d:any)=><View key={d.date} style={s.row}><Text style={s.label}>{d.date}</Text><Text style={s.rowValue}>🪙 {d.coinsEarned||0} · +{d.newFollowers||0} followers</Text></View>)}</ScrollView></AppShell>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:theme.bg,padding:18},back:{color:"#fff",fontSize:40},kicker:{color:theme.pinkSoft,fontSize:8,fontWeight:"900",letterSpacing:2},title:{color:"#fff",fontSize:29,fontWeight:"900"},error:{color:"#ff8bad",textAlign:"center",marginVertical:10},grid:{flexDirection:"row",flexWrap:"wrap",gap:9,marginTop:16},stat:{width:"48%",backgroundColor:theme.surface,borderRadius:16,padding:15,borderWidth:1,borderColor:"rgba(255,255,255,.07)"},value:{color:"#fff",fontSize:20,fontWeight:"900"},label:{color:theme.dim,fontSize:9,marginTop:4},section:{color:"#fff",fontSize:17,fontWeight:"900",marginTop:22,marginBottom:10},tools:{flexDirection:"row",flexWrap:"wrap",gap:8},tool:{padding:11,borderRadius:11,backgroundColor:theme.pink},toolText:{color:"#fff",fontSize:10,fontWeight:"900"},row:{flexDirection:"row",justifyContent:"space-between",padding:12,backgroundColor:theme.surface,borderRadius:11,marginBottom:6},rowValue:{color:theme.gold,fontSize:9,fontWeight:"900"},center:{flex:1,alignItems:"center",justifyContent:"center",backgroundColor:theme.bg}
});
