import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import AppShell from "../src/AppShell";
import { api } from "../src/phase2Api";

export default function Wallet(){
 const [wallet,setWallet]=useState<any>(null),[tx,setTx]=useState<any[]>([]),[packages,setPackages]=useState<any[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[error,setError]=useState("");
 const load=useCallback(async()=>{try{const [w,t,p]=await Promise.all([api.wallet(),api.walletTransactions(),api.coinPackages("mobile")]);setWallet(w);setTx(t||[]);setPackages(p||[]);}catch(e:any){setError(e.message||"Unable to load wallet.");}finally{setLoading(false);}},[]);
 useEffect(()=>{load();},[load]);
 const buy=async(p:any)=>{setBusy(p.id);try{const r=await api.checkout(p.id);if(r?.checkoutUrl) router.push({pathname:"/checkout",params:{url:r.checkoutUrl}});else await load();}catch(e:any){setError(e.message||"Unable to start checkout.");}finally{setBusy("");}};
 if(loading)return <AppShell><View style={s.center}><ActivityIndicator color={theme.pink}/></View></AppShell>;
 return <AppShell><ScrollView style={s.page} contentContainerStyle={{paddingBottom:40}}><Text style={s.kicker}>AMORA WALLET</Text><Text style={s.title}>Your balance.</Text><View style={s.hero}><Text style={s.coins}>🪙 {wallet?.balance||0}</Text><Text style={s.muted}>Available coins</Text><Pressable style={s.withdraw} onPress={()=>router.push("/withdraw")}><Text style={s.withdrawText}>Withdraw earnings</Text></Pressable></View>{!!error&&<Text style={s.error}>{error}</Text>}<Text style={s.section}>Buy coins</Text><View style={s.packages}>{packages.map(p=><Pressable key={p.id} disabled={busy===p.id} onPress={()=>buy(p)} style={s.package}><Text style={s.packageCoins}>🪙 {p.coins}</Text><Text style={s.price}>{p.currency||"USD"} {p.price}</Text><Text style={s.buy}>{busy===p.id?"…":"Buy"}</Text></Pressable>)}</View><Text style={s.section}>Recent activity</Text>{tx.slice(0,20).map((x,i)=><View key={x.id||i} style={s.row}><View style={{flex:1}}><Text style={s.rowTitle}>{x.description||x.type||"Wallet transaction"}</Text><Text style={s.muted}>{x.created_at?new Date(x.created_at).toLocaleDateString():""}</Text></View><Text style={[s.amount,{color:Number(x.amount||x.coins||0)>=0?theme.success:"#ff8080"}]}>{Number(x.amount||x.coins||0)>=0?"+":""}{x.amount||x.coins||0}</Text></View>)}</ScrollView></AppShell>;
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:theme.bg,padding:18},kicker:{color:theme.gold,fontSize:8,fontWeight:"900",letterSpacing:2},title:{color:"#fff",fontSize:30,fontWeight:"900",marginTop:5},hero:{backgroundColor:theme.surface,borderRadius:22,padding:20,marginTop:16,borderWidth:1,borderColor:"rgba(255,216,107,.18)"},coins:{color:theme.gold,fontSize:34,fontWeight:"900"},muted:{color:theme.muted,fontSize:9,marginTop:4},withdraw:{marginTop:15,backgroundColor:theme.purple,borderRadius:11,paddingVertical:11,alignItems:"center"},withdrawText:{color:"#fff",fontSize:10,fontWeight:"900"},error:{color:"#ff8bad",textAlign:"center",marginTop:10},section:{color:"#fff",fontSize:17,fontWeight:"900",marginTop:22,marginBottom:10},packages:{flexDirection:"row",flexWrap:"wrap",gap:8},package:{width:"48%",backgroundColor:theme.surface,borderRadius:16,padding:14,borderWidth:1,borderColor:"rgba(255,255,255,.07)"},packageCoins:{color:"#fff",fontSize:17,fontWeight:"900"},price:{color:theme.gold,fontSize:10,marginTop:4},buy:{color:theme.pink,fontSize:10,fontWeight:"900",marginTop:8},row:{flexDirection:"row",alignItems:"center",backgroundColor:theme.surface,borderRadius:13,padding:12,marginBottom:6},rowTitle:{color:"#fff",fontSize:10,fontWeight:"800"},amount:{fontWeight:"900",fontSize:11},center:{flex:1,alignItems:"center",justifyContent:"center",backgroundColor:theme.bg}
});
