import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { router } from "expo-router";
import AppShell from "../src/AppShell";
import { theme } from "../src/theme";
import { phase1Request } from "../src/phase1Api";

export default function Withdraw(){const [info,setInfo]=useState<any>(null),[history,setHistory]=useState<any[]>([]),[coins,setCoins]=useState(""),[method,setMethod]=useState("paypal"),[details,setDetails]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const load=useCallback(async()=>{try{const [i,h]=await Promise.all([phase1Request("/wallet/withdrawal-info"),phase1Request("/wallet/withdrawals")]);setInfo(i);setHistory(h||[]);}catch(e:any){setError(e.message||"Unable to load withdrawal information.");}finally{setLoading(false);}},[]);
 useEffect(()=>{load();},[load]);
 const submit=async()=>{setError("");setMessage("");const n=Number(coins);if(!Number.isInteger(n)||n<(info?.minWithdrawalCoins||0)){setError(`Minimum withdrawal is ${Number(info?.minWithdrawalCoins||0).toLocaleString()} coins.`);return;}if(n>(info?.balance||0)){setError("You cannot withdraw more than your balance.");return;}if(!details.trim()){setError("Enter your payout details.");return;}setBusy(true);try{const d=await phase1Request("/wallet/withdraw",{method:"POST",body:JSON.stringify({coinsAmount:n,payoutMethod:method,payoutDetails:details.trim()})});setMessage(`Withdrawal submitted for $${(Number(d.usd_cents || 0) / 100).toFixed(2)}.`);setCoins("");setDetails("");await load();}catch(e:any){setError(e.message||"Unable to submit withdrawal.");}finally{setBusy(false);}};
 if(loading)return <AppShell><View style={s.center}><ActivityIndicator color={theme.pink}/></View></AppShell>;
 return <AppShell><ScrollView style={s.page} contentContainerStyle={{paddingBottom:40}}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹</Text></Pressable><Text style={s.kicker}>AMORA CREATOR PAYOUTS</Text><Text style={s.title}>Withdraw</Text><View style={s.card}><Text style={s.balance}>🪙 {info?.balance||0}</Text><Text style={s.muted}>Minimum: {Number(info?.minWithdrawalCoins||0).toLocaleString()} coins · Rate: {info?.coinToUsdCents||0}¢ / coin</Text><Text style={s.label}>Coins amount</Text><TextInput keyboardType="number-pad" value={coins} onChangeText={setCoins} style={s.input} placeholder="1000" placeholderTextColor={theme.dim}/><Text style={s.label}>Payout method</Text><View style={s.methods}>{["paypal","bank"].map(x=><Pressable key={x} onPress={()=>setMethod(x)} style={[s.method,method===x&&s.active]}><Text style={s.methodText}>{x.toUpperCase()}</Text></Pressable>)}</View><Text style={s.label}>Payout details</Text><TextInput value={details} onChangeText={setDetails} style={s.input} placeholder="Email or bank details" placeholderTextColor={theme.dim}/><Pressable disabled={busy} onPress={submit} style={s.submit}><Text style={s.submitText}>{busy?"Submitting…":"Request withdrawal"}</Text></Pressable></View>{!!error&&<Text style={s.error}>{error}</Text>}{!!message&&<Text style={s.success}>{message}</Text>}<Text style={s.section}>History</Text>{history.map(h=><View key={h.id} style={s.row}><Text style={s.rowText}>{h.coins_amount} coins</Text><Text style={s.status}>{h.status}</Text></View>)}</ScrollView></AppShell>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:theme.bg,padding:18},back:{color:"#fff",fontSize:40},kicker:{color:theme.gold,fontSize:8,fontWeight:"900",letterSpacing:2},title:{color:"#fff",fontSize:29,fontWeight:"900"},card:{backgroundColor:theme.surface,borderRadius:20,padding:16,marginTop:16,borderWidth:1,borderColor:"rgba(255,255,255,.07)"},balance:{color:theme.gold,fontSize:28,fontWeight:"900"},muted:{color:theme.muted,fontSize:9,lineHeight:15,marginTop:4},label:{color:theme.dim,fontSize:9,marginTop:14,marginBottom:5},input:{backgroundColor:"#11101b",color:"#fff",borderRadius:10,padding:12,borderWidth:1,borderColor:"rgba(255,255,255,.08)"},methods:{flexDirection:"row",gap:7},method:{padding:10,borderRadius:10,backgroundColor:"#11101b"},active:{backgroundColor:theme.pink},methodText:{color:"#fff",fontSize:9,fontWeight:"900"},submit:{marginTop:16,backgroundColor:theme.pink,borderRadius:12,paddingVertical:13,alignItems:"center"},submitText:{color:"#fff",fontWeight:"900"},error:{color:"#ff8bad",textAlign:"center",marginTop:10},success:{color:theme.success,textAlign:"center",marginTop:10},section:{color:"#fff",fontSize:17,fontWeight:"900",marginTop:22,marginBottom:10},row:{flexDirection:"row",justifyContent:"space-between",backgroundColor:theme.surface,borderRadius:12,padding:12,marginBottom:6},rowText:{color:"#fff",fontSize:10},status:{color:theme.gold,fontSize:9,fontWeight:"900"},center:{flex:1,alignItems:"center",justifyContent:"center",backgroundColor:theme.bg}
});
